// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKCe1Ez1H6fJ7LseurdXriILT-zq7Cx1k',
    appId: '1:368553098599:web:b1a69afcf6f97f58d343c2',
    messagingSenderId: '368553098599',
    projectId: 'hangman-app-fm',
    authDomain: 'hangman-app-fm.firebaseapp.com',
    storageBucket: 'hangman-app-fm.appspot.com',
    measurementId: 'G-ZLYBDPQ0F0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiiruh65GT_gC8wnLmfsTcoEqewZfq3sQ',
    appId: '1:368553098599:android:80eddc8bf21aa3fbd343c2',
    messagingSenderId: '368553098599',
    projectId: 'hangman-app-fm',
    storageBucket: 'hangman-app-fm.appspot.com',
  );
}
